### ISSUE TITLE
Server Error ReferenceError: global is not defined

### ISSUE THREAD

**Issue by khentonx** [sweetscript/next-app-session#3]
Using middleware.js from Next.js I am getting this error when importing my session object from the session.ts/js file. 
![serverError](https://github.com/sweetscript/next-app-session/assets/109174430/2b381df9-c101-49e1-b985-524375a817e9)

**Comment by majidkuhail** [comment]
Hi @khentonx 
It seems you're using the default MemoryStore, This error would happen if you're calling the session in the client side instead of server side.

The Readme file has details on where you can use the session and how:

> Note: in App router, session can only read data in [Server Components](https://nextjs.org/docs/getting-started/react-essentials) while it can read+write data in [Route Handler](https://nextjs.org/docs/app/building-your-application/routing/router-handlers) and [Server Actions](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions). It follows the same usage rules as the [cookies() dynamic function](https://nextjs.org/docs/app/api-reference/functions/cookies)

If this is still an issue, please share the code from which you're calling the session file so I can investigate.

Thanks
